name: Actualizar Noticias

on:
  schedule:
    - cron: '*/15 * * * *' # Automático cada 15 minutos
  workflow_dispatch:    # Botón manual en la web
  # ESTO PERMITE QUE EL LUMIA DISPARE EL SCRIPT
  repository_dispatch:
    types: [activacion_desde_lumia]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install newspaper3k feedparser lxml_html_clean requests

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios
        run: |
          git config --global user.name "NewsBot"
          git config --global user.email "bot@github.com"
          git add noticias.json
          git commit -m "Noticias actualizadas via Lumia" || exit 0
          git push
